version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - TAG="$456789"
      - echo $TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag "842851603113.dkr.ecr.us-east-1.amazonaws.com/product-suite-name-product-name:${TAG}" .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 842851603113.dkr.ecr.us-east-1.amazonaws.com/product-suite-name-product-name:${TAG}
      - printf '{"tag":"%s"}' $TAG > build.json
      - echo $TAG
artifacts:
  files: '**/*'
  discard-paths: yes