version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t product-suite-name-product-name .
      - docker tag product-suite-name-product-name:latest 842851603113.dkr.ecr.us-east-1.amazonaws.com/product-suite-name-product-name:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 842851603113.dkr.ecr.us-east-1.amazonaws.com/product-suite-name-product-name:latest
artifacts:
  files: /tmp/*
  discard-paths: yes